name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          spago: "unstable" # "0.93.43" # "next"

      - run: spago build --strict --ensure-ranges --pedantic-packages

      - run: spago test --strict --pedantic-packages --offline
